import { Box, Heading, Link, Text } from "@chakra-ui/react";

const LandingPageTemplate = () => {
  return (
    <>
      <Box as="main">
        <Box as="section">
          <Heading>Reddit Apex</Heading>
        </Box>
      </Box>
      <Box as="footer">
        <Box as="section">
          <Text>
            Generated by{" "}
            <Link href="https://github.com/akd-io/create-next-stack">
              Create Next Stack
            </Link>
          </Text>
        </Box>
      </Box>
    </>
  );
};

export default LandingPageTemplate;
